sudo: false
language: node_js
node_js:
  - "v8.11.3"
addons:
  chrome: stable
before_install:
  - export CHROME_BIN=google-chrome-stable
  - export DISPLAY=:99.0
before_script:
  - npm install
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start
script:
  - ng test --watch=false
